name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust tool chain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Lint the code
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run the security audit check, ignoring known issue that is not relevant for this project
        uses: actions-rs/cargo@v1
        with:
          command: audit

      - name: Run the tests with the static target
        uses: actions-rs/cargo@v1
        with:
          command: test
